#!/usr/bin/env python3
"""
Pitch Coach — FastAPI HTTP sidecar for Floom proxy-runtime.

Wraps the existing main.py logic as an HTTP server so Floom can register
this app as a proxied app (app_type='proxied') without Docker.

Endpoints:
  GET  /health
  GET  /openapi.json  (auto-generated by FastAPI)
  POST /coach         — main action endpoint
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# Allow importing main.py from the same directory
sys.path.insert(0, str(Path(__file__).parent))

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field

import main as _coach

PORT = int(os.environ.get("PORT", "8000"))
HOST = os.environ.get("HOST", "0.0.0.0")

app = FastAPI(
    title="Pitch Coach",
    version="1.0.0",
    description=(
        "Paste a 20-500 char startup pitch. "
        "Get 3 direct critiques, 3 angle-specific rewrites, and a 1-line TL;DR."
    ),
    openapi_url="/openapi.json",
    docs_url="/docs",
)


class CoachInputs(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    pitch: str = Field(
        ...,
        description="Startup pitch to critique. 20-500 characters.",
        min_length=20,
        max_length=500,
    )


class HarshTruthItem(BaseModel):
    critique: str
    vc_reaction: str


class RewriteItem(BaseModel):
    angle: str
    pitch: str
    when_to_use: str


class CoachOutput(BaseModel):
    harsh_truth: list[HarshTruthItem]
    rewrites: list[RewriteItem]
    one_line_tldr: str
    dry_run: bool = False
    cache_hit: bool = False
    model: str = ""


@app.get("/health")
async def health() -> JSONResponse:
    return JSONResponse({"status": "ok"})


@app.post("/coach", response_model=CoachOutput)
async def coach_route(inputs: CoachInputs) -> dict:
    try:
        return _coach.coach(pitch=inputs.pitch)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except TimeoutError as exc:
        raise HTTPException(status_code=504, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=str(exc)) from exc


if __name__ == "__main__":
    uvicorn.run(
        "server:app",
        host=HOST,
        port=PORT,
        log_level=os.environ.get("LOG_LEVEL", "info"),
    )
