// `floom init` scaffolds a floom.yaml (or validates an existing openapi.yaml)
// in the current working directory.
//
// Scope is deliberately tight: detect + stub. The command reads the cwd,
// makes a best guess at what kind of app lives there, writes a minimal
// manifest, and reports what it wrote so the user can review and edit.
// Heavy lifting (parsing OpenAPI, inferring inputs from request schemas,
// generating full op lists from Docker routes) is out of scope for v1. If
// the shape isn't obvious we fall back to a runnable skeleton the user
// can hand-edit.
//
// Paired with /docs/prepare-with-claude on the web side: that page gives
// users a prompt they can drop into Claude Code; the prompt references
// this command so agent + CLI converge on the same output.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

// ── Detection ─────────────────────────────────────────────────────────────

export type AppKind = 'openapi' | 'docker' | 'node' | 'python' | 'script' | 'unknown';

export interface Detection {
  kind: AppKind;
  /** Files we found that led to the conclusion. For user transparency. */
  evidence: string[];
  /** Path of an existing OpenAPI spec relative to cwd, if found. */
  openapiPath?: string;
  /** Best-guess app name derived from package.json, pyproject.toml, or dir name. */
  name: string;
}

const OPENAPI_CANDIDATES = [
  'openapi.yaml',
  'openapi.yml',
  'openapi.json',
  'api/openapi.yaml',
  'api/openapi.yml',
  'api/openapi.json',
  'spec/openapi.yaml',
  'docs/openapi.yaml',
];

export function detect(cwd: string): Detection {
  const evidence: string[] = [];
  let openapiPath: string | undefined;

  // 1. OpenAPI beats everything if it exists, Floom can import directly.
  for (const candidate of OPENAPI_CANDIDATES) {
    if (existsSync(resolve(cwd, candidate))) {
      openapiPath = candidate;
      evidence.push(candidate);
      break;
    }
  }

  const hasDockerfile = existsSync(resolve(cwd, 'Dockerfile'));
  const hasCompose =
    existsSync(resolve(cwd, 'docker-compose.yml')) ||
    existsSync(resolve(cwd, 'compose.yml'));
  const hasPackageJson = existsSync(resolve(cwd, 'package.json'));
  const hasRequirements = existsSync(resolve(cwd, 'requirements.txt'));
  const hasPyproject = existsSync(resolve(cwd, 'pyproject.toml'));

  if (hasDockerfile) evidence.push('Dockerfile');
  if (hasCompose) evidence.push('docker-compose.yml');
  if (hasPackageJson) evidence.push('package.json');
  if (hasRequirements) evidence.push('requirements.txt');
  if (hasPyproject) evidence.push('pyproject.toml');

  let kind: AppKind = 'unknown';
  if (openapiPath) kind = 'openapi';
  else if (hasDockerfile || hasCompose) kind = 'docker';
  else if (hasPackageJson) kind = 'node';
  else if (hasRequirements || hasPyproject) kind = 'python';
  else if (evidence.length > 0) kind = 'script';

  const name = inferName(cwd, hasPackageJson);

  return { kind, evidence, openapiPath, name };
}

function inferName(cwd: string, hasPackageJson: boolean): string {
  if (hasPackageJson) {
    try {
      const pkg = JSON.parse(readFileSync(resolve(cwd, 'package.json'), 'utf8'));
      if (typeof pkg.name === 'string' && pkg.name.length > 0) {
        // Scoped packages: strip the scope for the slug.
        return String(pkg.name).replace(/^@[^/]+\//, '');
      }
    } catch {
      // fall through to dir name
    }
  }
  return basename(cwd).toLowerCase().replace(/[^a-z0-9-]+/g, '-');
}

// ── Manifest stubs ────────────────────────────────────────────────────────

function stubForDocker(name: string): string {
  return `# Floom manifest, generated by \`floom init\`.
# Review and edit before running the import.
# Spec: https://floom.dev/protocol
name: ${name}
displayName: ${titleCase(name)}
description: TODO describe what this app does in one sentence.
runtime: docker
# TODO point this at the image you publish for your service.
image: ghcr.io/your-org/${name}:latest
ops:
  - name: run
    description: TODO what this op does.
    inputs:
      - name: payload
        type: json
        required: true
        description: Request body your service expects.
    output:
      type: json
`;
}

function stubForNode(name: string): string {
  return `# Floom manifest, generated by \`floom init\`.
# Review and edit before running the import.
# Spec: https://floom.dev/protocol
name: ${name}
displayName: ${titleCase(name)}
description: TODO describe what this app does in one sentence.
runtime: node
entry: index.js
ops:
  - name: run
    description: TODO what this op does.
    inputs:
      - name: input
        type: string
        required: true
        description: Main input the script takes.
        from: argv
    output:
      type: stdout
`;
}

function stubForPython(name: string): string {
  return `# Floom manifest, generated by \`floom init\`.
# Review and edit before running the import.
# Spec: https://floom.dev/protocol
name: ${name}
displayName: ${titleCase(name)}
description: TODO describe what this app does in one sentence.
runtime: python
entry: main.py
ops:
  - name: run
    description: TODO what this op does.
    inputs:
      - name: input
        type: string
        required: true
        description: Main input the script takes.
        from: argv
    output:
      type: stdout
`;
}

function stubForScript(name: string): string {
  return `# Floom manifest, generated by \`floom init\`.
# Review and edit before running the import.
# Spec: https://floom.dev/protocol
name: ${name}
displayName: ${titleCase(name)}
description: TODO describe what this app does in one sentence.
runtime: script
# TODO set this to the command that runs your app (e.g. \`bash run.sh\`).
command: echo "replace me"
ops:
  - name: run
    description: TODO what this op does.
    inputs:
      - name: input
        type: string
        required: true
        from: stdin
    output:
      type: stdout
`;
}

function titleCase(slug: string): string {
  return slug
    .split(/[-_]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ');
}

// ── Command ───────────────────────────────────────────────────────────────

export interface InitOptions {
  cwd?: string;
  force?: boolean;
}

export interface InitResult {
  action: 'skipped-openapi' | 'wrote-manifest' | 'exists';
  kind: AppKind;
  targetFile: string;
  evidence: string[];
  message: string;
}

export function runInit(options: InitOptions = {}): InitResult {
  const cwd = options.cwd ? resolve(options.cwd) : process.cwd();
  const det = detect(cwd);

  // If an OpenAPI spec is already at a sane path, Floom can import as-is.
  // The one thing we insist on is that the spec is at the repo root named
  // openapi.yaml (or .json) that's what the importer looks for first.
  if (det.kind === 'openapi' && det.openapiPath) {
    const atRoot =
      det.openapiPath === 'openapi.yaml' ||
      det.openapiPath === 'openapi.yml' ||
      det.openapiPath === 'openapi.json';
    if (atRoot) {
      return {
        action: 'skipped-openapi',
        kind: det.kind,
        targetFile: det.openapiPath,
        evidence: det.evidence,
        message:
          `Found ${det.openapiPath} at the repo root. Nothing to do. ` +
          `The Floom importer will pick this up directly.`,
      };
    }
    return {
      action: 'skipped-openapi',
      kind: det.kind,
      targetFile: det.openapiPath,
      evidence: det.evidence,
      message:
        `Found an OpenAPI spec at ${det.openapiPath}. Move or symlink it to ` +
        `openapi.yaml at the repo root so the Floom importer can find it, ` +
        `then run the import again.`,
    };
  }

  const targetFile = 'floom.yaml';
  const targetPath = resolve(cwd, targetFile);

  if (existsSync(targetPath) && !options.force) {
    return {
      action: 'exists',
      kind: det.kind,
      targetFile,
      evidence: det.evidence,
      message:
        `floom.yaml already exists in this directory. Re-run with --force to ` +
        `overwrite, or edit it by hand. No changes made.`,
    };
  }

  let stub: string;
  switch (det.kind) {
    case 'docker':
      stub = stubForDocker(det.name);
      break;
    case 'node':
      stub = stubForNode(det.name);
      break;
    case 'python':
      stub = stubForPython(det.name);
      break;
    case 'script':
    case 'unknown':
    default:
      stub = stubForScript(det.name);
      break;
  }

  writeFileSync(targetPath, stub, 'utf8');

  return {
    action: 'wrote-manifest',
    kind: det.kind,
    targetFile,
    evidence: det.evidence,
    message:
      `Wrote ${targetFile} (runtime: ${det.kind === 'unknown' ? 'script' : det.kind}). ` +
      `Open it, fill in the TODOs, commit, then retry the import at ` +
      `https://floom.dev/studio/build.`,
  };
}

export function formatResult(result: InitResult): string {
  const lines: string[] = [];
  lines.push(result.message);
  if (result.evidence.length > 0) {
    lines.push('');
    lines.push('Detected:');
    for (const item of result.evidence) {
      lines.push(`  - ${item}`);
    }
  }
  return lines.join('\n');
}
