#!/usr/bin/env python3
"""
AI Readiness Audit — FastAPI HTTP sidecar for Floom proxy-runtime.

Wraps the existing main.py logic as an HTTP server so Floom can register
this app as a proxied app (app_type='proxied') without Docker.

Endpoints:
  GET  /health
  GET  /openapi.json  (auto-generated by FastAPI)
  POST /audit         — main action endpoint
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# Allow importing main.py from the same directory
sys.path.insert(0, str(Path(__file__).parent))

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field

import main as _audit_main

PORT = int(os.environ.get("PORT", "8000"))
HOST = os.environ.get("HOST", "0.0.0.0")

app = FastAPI(
    title="AI Readiness Audit",
    version="1.0.0",
    description=(
        "Paste a public HTTPS company URL. "
        "Get a readiness score 0-10, 3 risks, 3 opportunities, and one concrete next step."
    ),
    openapi_url="/openapi.json",
    docs_url="/docs",
)


class AuditInputs(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    company_url: str = Field(
        ...,
        description="Public HTTPS URL only. Max 200 characters.",
        max_length=200,
    )


class AuditOutput(BaseModel):
    company_url: str
    readiness_score: int
    score_rationale: str
    risks: list[str]
    opportunities: list[str]
    next_action: str
    dry_run: bool = False
    cache_hit: bool = False
    model: str = ""


@app.get("/health")
async def health() -> JSONResponse:
    return JSONResponse({"status": "ok"})


@app.post("/audit", response_model=AuditOutput)
async def audit_route(inputs: AuditInputs) -> dict:
    # Call the async internals directly instead of audit() which wraps with
    # asyncio.run() — that would fail when called from FastAPI's event loop.
    try:
        return await _audit_main._audit_async(inputs.company_url)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except TimeoutError as exc:
        raise HTTPException(status_code=504, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=str(exc)) from exc


if __name__ == "__main__":
    uvicorn.run(
        "server:app",
        host=HOST,
        port=PORT,
        log_level=os.environ.get("LOG_LEVEL", "info"),
    )
