#!/usr/bin/env python3
"""
Competitor Lens — FastAPI HTTP sidecar entry point for Floom proxy-runtime.

main.py already defines the FastAPI `app` with /analyze, /run, and /openapi.json.
This script just starts uvicorn on the PORT env var so the launch-week-sidecars
service can fork it the same way it does Node.js sidecars.

Endpoints (from main.py):
  GET  /health        — (added below, main.py doesn't have it)
  GET  /openapi.json  — auto-generated by FastAPI
  POST /analyze       — main action endpoint
  POST /run           — Floom CLI-contract wrapper
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# Allow importing main.py from the same directory
sys.path.insert(0, str(Path(__file__).parent))

import uvicorn
from fastapi.responses import JSONResponse

from main import app  # noqa: E402 — after sys.path patch

PORT = int(os.environ.get("PORT", "8000"))
HOST = os.environ.get("HOST", "0.0.0.0")


@app.get("/health")
async def health() -> JSONResponse:
    return JSONResponse({"status": "ok"})


if __name__ == "__main__":
    uvicorn.run(
        "server:app",
        host=HOST,
        port=PORT,
        log_level=os.environ.get("LOG_LEVEL", "info"),
    )
